indico/indico-plugins

vc_vidyo/indico_vc_vidyo/blueprint.py
vc_vidyo/indico_vc_vidyo/controllers.py
vc_vidyo/indico_vc_vidyo/plugin.py
vc_vidyo/indico_vc_vidyo/static/js/vc_vidyo.js
vc_vidyo/indico_vc_vidyo/templates/buttons.html
vc_vidyo/indico_vc_vidyo/templates/event_buttons.html
vc_vidyo/indico_vc_vidyo/templates/info_box.html
vc_vidyo/indico_vc_vidyo/templates/manage_event_info_box.html
vc_vidyo/indico_vc_vidyo/templates/management_buttons.html
vc_vidyo/indico_vc_vidyo/templates/vc_room_timetable_buttons.html

- make me owner now sets the owner identity correctly in the vc_room data
- fixes #9
- "make me owner" relies on the connected user rather than a user id provided by the client
- renames the macro `make_me_moderator` to `make_me_owner`
- small modification in a flash message in Indico for consistency: indico/indico#1879

VC/Vidyo: Fix make me owner

---

livesync/indico_livesync/marcxml.py
livesync/indico_livesync/uploader.py
livesync/tests/uploader_test.py

Until now we were fetching livesync queu entries in batches but the resulting number of actual resulting records could be much higher

Livesync: Upload metadata records in batches

---

vc_vidyo/indico_vc_vidyo/api/cache.py
vc_vidyo/indico_vc_vidyo/api/client.py
vc_vidyo/indico_vc_vidyo/plugin.py
vc_vidyo/setup.py

It seems like suds' handling of Vidyo WSDL is broken.
[zeep](http://docs.python-zeep.org/en/master/) seems to be its rightful successor, kept up-to-date and designed in a more Pythonic way.

VC/Vidyo: use zeep instead of suds

---

livesync/indico_livesync/handler.py
livesync/setup.py

AFAIK it only matters whether someone can access an object or not - but not whether they are a manager or just have read access.

LiveSync: Ignore unrelated ACL changes

---

storage_xrootd/indico_storage_xrootd.py
storage_xrootd/setup.py

This is mainly useful for Indico instances at CERN, but also for anyone else who happens to have an XRootD/EOS storage system and wants to use it in indico.

WIP: Add xrootd/eos storage plugin

---

payment_manual/indico_payment_manual/__init__.py
payment_manual/indico_payment_manual/placeholders.py
payment_manual/indico_payment_manual/plugin.py
payment_manual/indico_payment_manual/templates/event_payment_form.html
payment_manual/setup.py

This pull request is still WIP and aims at supporting the following placeholders in the payment description of the payment_manual plugin:
Placeholder | Replacement
------------|---------------
{event_id} | replaced by the ID of the vent
{registration_id} | replaced by the friendly ID of the registration
{first_name} | replaced by the first name of the registrant
{last_name} | repalced by the last name of the registrant
A unique ID per registration will probably be added later (not part of this PR).

payment_manual: implementation of placeholders in description

---

payment_manual/indico_payment_manual/placeholders.py
payment_manual/indico_payment_manual/plugin.py
payment_manual/setup.py

Suggested change to 'indico-plugins' plugin named 'payment_manual' that adds Email as a field placeholder that can be added into the 'Payment details' text box when configuring the manual payment for an event

Add Email Placeholder

---

storage_s3/indico_storage_s3/storage.py
storage_s3/setup.py

Otherwise it's impossible to store files larger than 5GB. We always include the header with the checksum now, because there is no harm in doing so and otherwise we'd have to first check how large the file we're storing is...
closes #87

Storage/S3: Use high-level API supporting chunks

---

vc_zoom/indico_vc_zoom/plugin.py

Show the detailed error message from the Zoom API when failing to delete a meeting.

VC/Zoom: Show detailed error when deleting meeting

---

vc_zoom/README.md
vc_zoom/indico_vc_zoom/plugin.py

We can most likely use the same APIs as in #71 for this.
Important: This must not expose private join links (with the passcode included) to people who would otherwise not have access. We may need to include the user in the `metadata_postprocess` signal since in case of a call through the HTTP API we do not have a `session.user`.

Include Zoom join URL(s) in ICAL files

---

livesync/indico_livesync/base.py
livesync/indico_livesync/cli.py
livesync/indico_livesync/initial.py
livesync/indico_livesync/uploader.py
livesync/tests/agent_test.py

Our previously indexing mechanism didn't account for any records. 
This PR intends to include all the main entities, such as Events, Contributions, etc...
Since indexing based on lazy-loaded attributes would potentially generate multiple queries and slow down the process, we had to forcibly break down some of those relations into the complex queries here.

LiveSync: Eager load schemas in initial exports

---

citadel/indico_citadel/backend.py
citadel/indico_citadel/cli.py
citadel/indico_citadel/migrations/20210330_1742_0cf18be7ade1_add_mapping_table.py
citadel/indico_citadel/models/id_map.py

`search_id` was always a bit strange, so I'm using `citadel_id` now.
Also, the table name is closer to the model name now.

Citadel: Rename model/table

---

citadel/indico_citadel/search.py

While debating on whether we should keep these placeholders (and i18n) supported by Indico or provided by the plugin, I've decided to go for the latter as different search providers may support distinct placeholders.

Integrate placeholders with Indico

---

citadel/indico_citadel/search.py
citadel/indico_citadel/util.py
citadel/indico_citadel/util_test.py

Even though we don't need to pass the filters into Indico, as most of them come directly within the result aggregations, having them available is useful for providing i18n or getting their name from the query string.
Having a pre-defined list of them available through Indico or the search plugin is discussible. Even though I think it makes more sense the latter, as this PR, since they should change between implementations.

Citadel: Integrate filters with Indico and update placeholders

---

citadel/indico_citadel/backend.py
citadel/indico_citadel/cli.py
citadel/indico_citadel/util.py

The previous thread pool implementation launched n threads but then waited for all of them to finish before launching the next n. This one processes the data constantly instead of waiting for a full batch to finish.

Use all worker threads all the time

---

citadel/indico_citadel/backend.py
citadel/indico_citadel/cli.py
citadel/indico_citadel/plugin.py
livesync/indico_livesync/uploader.py
livesync/tests/uploader_test.py
livesync_debug/indico_livesync_debug/backend.py

Smaller instances don't need hundreds of threads, and for regular queue runs we don't need that many threads either.
I also used lower retry limits for regular queue runs since they just restart 15min later in case of a failure anyway.

Citadel: Make thread counts configurable

---

livesync/indico_livesync/simplify.py
livesync/tests/simplify_test.py
livesync/tests/uploader_test.py

When cloning an event, there's just a creation record for the event itself, but cascading creates creation records for all its child objects (e.g. contributions).
Now, when such a contribution gets deleted WITHOUT a livesync run in between, we have the event creation record and a contribution deletion record. But when cascading the creation, usually deleted objects are skipped, so we'd try to delete something from the search service that doesn't exist there.
With this change we cascade creations even to deleted child objects, so the implicit creation and the explicit deletion cancel itself out as expected.

LiveSync: Correctly cascade deletions after cloning

---

citadel/indico_citadel/backend.py
livesync/indico_livesync/base.py
livesync/indico_livesync/cli.py
livesync/indico_livesync/plugin.py
livesync/indico_livesync/simplify.py
livesync/tests/agent_test.py
livesync_debug/indico_livesync_debug/backend.py

Those can result in huge (hundred thousands of updates) in case of larger instances like ours, so when someone is making large changes we may want to pause processing them and wait until all changes to a set of categories are done, and also have the ability to run those in foreground instead of during the regular queue runs.
Also fixed a bug where we were cascading category changes to events in blacklisted categories.

LiveSync: Add setting to skip category queue entries

---

livesync/indico_livesync/handler.py
livesync/indico_livesync/migrations/20210608_1713_ff1323696f67_add_published_change_type.py
livesync/indico_livesync/models/queue.py
livesync/indico_livesync/simplify.py
livesync/tests/simplify_test.py

Delete events from search when moving to a blacklisted category, and create then when moving out of such a category.

LiveSync: Correctly handling category blacklist during moves

---

livesync/indico_livesync/handler.py
livesync/indico_livesync/models/queue.py
livesync/setup.cfg

This PR adds `None` category checks for the livesync plugin.

Fixes for unlisted events on livesync plugin

---

vc_zoom/indico_vc_zoom/plugin.py

Comes from https://github.com/indico/indico-plugins/pull/157#discussion_r739575233. Avoids duplicated bundle in the videoconference page.

Change bundle injection to WPConferenceDisplay

---

citadel/pytest.ini
livesync/pytest.ini
payment_paypal/pytest.ini
storage_s3/pytest.ini
vc_zoom/pytest.ini

Celery is using an invalid legacy version specifier (celery/celery#7074)

Fix DeprecationWarning breaking tests

---

manage-i18n.sh

The new usage is:
```
./manage-i18n.sh [init <locale>|extract|update <locale>|compile <locale>] [plugin...]
```

Add a plugin list parameter to the i18n script

---

vc_zoom/README.md
vc_zoom/indico_vc_zoom/plugin.py

Part 2 of 2 of https://github.com/indico/indico/issues/5166
Part 1: https://github.com/indico/indico/pull/5211
This part adds `skip_access_check` parameter to allow
adding zoom details in reminders.

Add 'skip_access_check' parameter

---

vc_zoom/README.md
vc_zoom/indico_vc_zoom/plugin.py
vc_zoom/setup.cfg

iCalendar files for events and categories are no longer generated through the API in recent Indico versions and other consumers of the API (scripts etc) typically do not expect Zoom links in there.

Do not inject zoom links in HTTP API responses

---

owncloud/MANIFEST.in
owncloud/README.md
owncloud/indico_owncloud/__init__.py
owncloud/indico_owncloud/blueprint.py
owncloud/indico_owncloud/client/index.js
owncloud/indico_owncloud/client/style.scss
owncloud/indico_owncloud/controllers.py
owncloud/indico_owncloud/forms.py
owncloud/indico_owncloud/plugin.py
owncloud/indico_owncloud/templates/add_owncloud_files.html
owncloud/indico_owncloud/templates/owncloud_button.html
owncloud/indico_owncloud/templates/owncloud_filepicker_widget.html
owncloud/indico_owncloud/translations/messages.pot
owncloud/indico_owncloud/util.py
owncloud/setup.cfg
owncloud/setup.py
owncloud/webpack-bundles.json

This PR adds a plugin to integrate CERNBox (or any other ownCloud instance) into Indico. The integration enables event managers to attach materials from their cloud storage into events and categories, via a file picker service which is hosted in the storage server.
The plugin adds a button to the event materials management page, as well as the category materials management page. 
This button with open a new dialog similar to the file upload which enables users to pick files from their storage provider and finally copies them into the Indico server.
To enable the plugin, a URL for the file-picker which the attachments will come from is required. It can be specified in the plugin settings, under the administration area.
In there, the 'add material' button caption and icon can also be …

Add ownCloud integration plugin

---

owncloud/README.md
owncloud/indico_owncloud/templates/owncloud_filepicker_widget.html

This PR adds the `userHome` and `style` search params to the Indico OwnCloud plugin file-picker iframe so it starts in the user home instead of eos root, and uses the Indico CSS.

OwnCloud: Add configuration params to file-picker URL

---

owncloud/README.md
owncloud/indico_owncloud/client/index.js
owncloud/indico_owncloud/forms.py
owncloud/indico_owncloud/templates/owncloud_filepicker_widget.html
owncloud/setup.cfg

This PR disables the 'Add' button in the 'Add files' dialog for the ownCloud plugin while the File-picker is performing async operations.
This fixes the bug caused by a user clicking too fast on "Add" after selecting a file, where he would get notified that there are no files selected.

Disable add files button when not ready

---

vc_zoom/README.md
vc_zoom/indico_vc_zoom/plugin.py
vc_zoom/setup.cfg

`mute_host_video` is the negation of zoom's `host_video`.

Fix 'Mute video (host)' in room settings

---

.github/workflows/ci.yml

`set-output` and `save-state` will fail to work in June 2023: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Note: Action versions can also be kept up-to-date via dependapot in case you prefer automation, see e.g.:
https://github.com/unibonn/indico-sso-group-mapping/blob/ed9eb4264988880fa3abe9fc5d48f589637e0fb0/.github/dependabot.yml

ci: bump versions of actions and update depcrecated syntax

---

cloud_captchas/indico_cloud_captchas/client/i18n.js

When `Param` is imported directly from `react-jsx-i18n`, webpack probably creates a different instance
which leads to this error when running it (originally found by Duarte):
https://github.com/indico/react-jsx-i18n/blob/4b62533d907c2ae6356db6a1a65c1f64860bb90f/src/client/index.js#L42C38-L42C38

[cloud_captchas] Import translation components from Indico

---

.github/workflows/ci.yml

Otherwise we can get problems when the setup job runs on a different patch release than the test/lint job because the symlink in the venv points to an exact x.y.z release

ci: Use exact Python version

---

citadel/MANIFEST.in
citadel/README.md
citadel/indico_citadel/plugin.py
citadel/indico_citadel/templates/event_category_warning.html
citadel/indico_citadel/util.py

This PR implements a warning message that is displayed to category admins when the total count of events in said category goes over a configurable threshold. The warning message will recommend admins to use groups instead.
TODO:
Preview:

Citadel: Implement warning threshold

---

.github/utils/check_version.py
.github/workflows/pypi.yml

This is for "general" releases that bump the versions of all plugins.
For the first release where everything goes to v3.3 this will publish everything, for future releases (v3.3.x) which will only update some plugins, any wheel that already exists on PyPI with the same version should simply be skipped.
Intermediate releases where just specific plugins get updated (within the allowed range of the `indico-plugins` meta package) are **not handled** by this job. We'll have to add a separate one that's either triggered manually (not ideal), from pushes that bump the version of a plugin (maybe a bit too implicit?) or start creating tags for individual plugin releases (`vc-zoom/v3.3.1` or similar).

ci: Publish to PyPI from tags

---

payment_sixpay/README.md
payment_sixpay/indico_payment_sixpay/forms.py

Hi, we received a new saferpay id last week. the new id is one digit longer than the validator supports. Don't think it will have negative impact on anyone having the validator allow one more digit.

fix saferpay: new saferpay ids are one digit longer

---

vc_zoom/README.md
vc_zoom/indico_vc_zoom/plugin.py
vc_zoom/indico_vc_zoom/task.py
vc_zoom/indico_vc_zoom/util.py

When people convert it directly on Zoom, Indico may not be aware of this, and thus use the wrong APIs which do not work.
Now we always check the state on Zoom, and use that. There's a minor overhead for webinars since we query the meeting API first, but for the vast majority of events that use normal meetings this won't make a difference.

VC/Zoom: Get meeting/webinar type from Zoom

---

themes_legacy/README.md
themes_legacy/indico_themes_legacy/templates/compact_timetable.html
themes_legacy/pyproject.toml

There are some extra empty parens when the room name is not set.
now:
with the fix:

Fix room name display in the compact theme

---

citadel/README.md
citadel/indico_citadel/backend.py

These are all fixes I put in production some weeks ago:
- Avoid excessively long retry backoff delays
- Do not spam thousands of warnings to sentry
- Do not fail when a record cannot be deleted from Citadel persistently

Citadel: Fix issues during queue runs

---

citadel/README.md
citadel/indico_citadel/schemas.py
citadel/indico_citadel/util.py
citadel/pyproject.toml
vc_zoom/README.md
vc_zoom/indico_vc_zoom/controllers.py
vc_zoom/indico_vc_zoom/forms.py
vc_zoom/indico_vc_zoom/notifications.py
vc_zoom/indico_vc_zoom/plugin.py
vc_zoom/indico_vc_zoom/templates/buttons.html
vc_zoom/indico_vc_zoom/util.py
vc_zoom/pyproject.toml

In places where the identifiers are stored in a persistent way we now need to use the `persistent_identifier` which is basically the old `identifier` without a signature.
depends on indico/indico#6952

Adapt plugins to signed user identifiers
