indico/indico-plugins

chat/indico_chat/templates/manage_event.html
> **NOTE**
To be merged together with indico/indico#1941
=> Fix icon's name from icomoon

previewer_code/MANIFEST.in, previewer_code/indico_previewer_code/__init__.py, previewer_code/indico_previewer_code/plugin.py, previewer_code/indico_previewer_code/templates/pygments_preview.html, previewer_code/setup.py, previewer_jupyter/MANIFEST.in, previewer_jupyter/indico_previewer_jupyter/__init__.py, previewer_jupyter/indico_previewer_jupyter/blueprint.py, previewer_jupyter/indico_previewer_jupyter/controllers.py, previewer_jupyter/indico_previewer_jupyter/cpp_highlighter.py, previewer_jupyter/indico_previewer_jupyter/plugin.py, previewer_jupyter/indico_previewer_jupyter/templates/iframe_preview.html, previewer_jupyter/indico_previewer_jupyter/templates/ipynb_preview.html, previewer_jupyter/setup.py
This shouldn't be merged into v1.9.5.
=> Add plugins for code highlighting (Pygments) and IPython/Jupyter notebook rendering

previewer_jupyter/indico_previewer_jupyter/controllers.py, previewer_jupyter/indico_previewer_jupyter/templates/ipynb_preview.html
Won't work without unsafe-eval CSP :/
=> Jupyter: added default sane MathJax config

chat/indico_chat/plugin.py, livesync/indico_livesync/plugin.py
Merge together with https://github.com/indico/indico/pull/2270
=> Adapt settings forms to MultipleItemsField changes

importer/indico_importer/controllers.py, importer/indico_importer/plugin.py, importer/indico_importer/static/js/importer.js, importer_invenio/indico_importer_invenio/converters.py
Same as #27 but against master instead of devel.
=> Adapt importer to new timetable

livesync/indico_livesync/cli.py, livesync/indico_livesync/handler.py, livesync/indico_livesync/marcxml.py, livesync/indico_livesync/migrations/201607131557_230c086da074_use_foreign_key_for_categories.py, livesync/indico_livesync/migrations/201607151736_205f944640f6_add_session_to_livesyncqueueentry.py, livesync/indico_livesync/models/queue.py, livesync/indico_livesync/simplify.py, livesync/indico_livesync/uploader.py, livesync/indico_livesync/util.py, livesync/tests/agent_test.py, livesync/tests/conftest.py, livesync/tests/queue_test.py, livesync/tests/simplify_test.py, livesync/tests/uploader_test.py, livesync/tests/util_test.py, livesync_debug/indico_livesync_debug/backend.py
Simplified the way records are processed.
See also https://github.com/indico/indico/pull/2545.
Missing:
=> LiveSync - link to categories and sessions

chat/indico_chat/controllers/management.py, chat/indico_chat/templates/manage_event.html, chat/indico_chat/templates/manage_event_edit.html
Part of issue: indico/indico#2596
=> Move forms from page to dialog

search/indico_search/plugin.py, search/indico_search/templates/searchbox_conference.html
Merge alongside with https://github.com/indico/indico/pull/2741
=> Fix search bar style in conference pages

vc_vidyo/indico_vc_vidyo/http_api.py, vc_vidyo/indico_vc_vidyo/plugin.py
After testing with Rene and had agreed format of the output.
=> Vc vidyo removing obsolete vc rooms

livesync/indico_livesync/handler.py
=> Changes related to indico/indico#2833

search/indico_search/forms.py, search/indico_search/templates/results.html, search/setup.py
Related to https://github.com/indico/indico/pull/3063
=> Replace DateField with IndicoDateField

_meta/extras.yaml, _meta/setup.py, chat/setup.py, importer/setup.py, importer_invenio/setup.py, livesync/setup.py, livesync_debug/setup.py, livesync_invenio/setup.py, payment_manual/setup.py, payment_paypal/setup.py, piwik/setup.py, previewer_code/setup.py, previewer_jupyter/setup.py, search/setup.py, search_invenio/setup.py, storage_xrootd/setup.py, update-meta.py, vc_dummy/setup.py, vc_vidyo/setup.py
- also includes a script to update it
- renames plugins from `indico_*` to `indico-plugin-*`
=> Add meta package

payment_paypal/indico_payment_paypal/plugin.py, payment_paypal/indico_payment_paypal/templates/event_settings_encoding_warning.html, payment_paypal/setup.py
=> Payment/Paypal: add warning about UTF-8 config

search/indico_search/client/index.js, search/indico_search/client/main.scss
=> Fix height/width visual bugs in search tag

livesync/indico_livesync/controllers.py, livesync/indico_livesync/util.py, piwik/indico_piwik/reports.py, piwik/setup.py, search/indico_search/controllers.py, search/setup.py
Apply changes included in https://github.com/indico/indico/pull/4426.
=> Rename get_one(...) -> get_or_404(...)

vc_zoom/README.md, vc_zoom/indico_vc_zoom/forms.py, vc_zoom/indico_vc_zoom/templates/buttons.html, vc_zoom/indico_vc_zoom/templates/info_box.html, vc_zoom/indico_vc_zoom/templates/management_buttons.html
Also fixing the `is_manager` logic in order to actually check for management access instead of being in the management area.
=> Add option to show passcode only to registered participants

vc_zoom/README.md, vc_zoom/indico_vc_zoom/plugin.py, vc_zoom/indico_vc_zoom/templates/extra_delete_msg.html
=> VC/Zoom: Warn on deletion if user is not the host

vc_zoom/README.md, vc_zoom/indico_vc_zoom/plugin.py
=> VC/Zoom: set room recurrence when cloning event

vc_zoom/README.md, vc_zoom/indico_vc_zoom/controllers.py, vc_zoom/indico_vc_zoom/plugin.py, vc_zoom/indico_vc_zoom/translations/messages.pot, vc_zoom/indico_vc_zoom/util.py
Related to https://github.com/indico/indico/pull/4764
=> Zoom: do not clone deleted meetings/VCRooms

vc_zoom/README.md, vc_zoom/indico_vc_zoom/controllers.py, vc_zoom/indico_vc_zoom/plugin.py
Otherwise any change made outside Indico would be overwritten with the data stored in Indico.
=> Always refresh zoom data before making changes

livesync/indico_livesync/base.py, livesync/indico_livesync/cli.py, livesync/indico_livesync/initial.py, livesync/indico_livesync/uploader.py, livesync/tests/agent_test.py, livesync/tests/uploader_test.py
=> Livesync: Include subcontributions in the initial export

citadel/indico_citadel/search.py
Reflects the changes in indico/indico#4886
=> Update the search API to support multiple types

.github/workflows/ci.yml, storage_s3/indico_storage_s3/storage.py, storage_s3/pytest.ini, storage_s3/tests/plugin_test.py
Also run the s3 plugin tests in CI...
=> Storage/S3: Fix dynamic bucket hashing

citadel/indico_citadel/search.py, citadel/indico_citadel/util.py
=> Citadel: Move get_user_access to plugin

livesync/indico_livesync/handler.py, livesync/indico_livesync/migrations/20210602_1307_330e32d26232_add_undeleted_change_type.py, livesync/indico_livesync/models/queue.py, livesync/indico_livesync/simplify.py, livesync/tests/simplify_test.py, livesync/tests/uploader_test.py
=> LiveSync: Track undeletions/restores

citadel/indico_citadel/search.py, citadel/indico_citadel/util.py
Related to https://github.com/indico/indico/issues/4912.
=> Add allow_admin parameter

livesync/README.md, livesync/indico_livesync/cli.py, livesync/setup.cfg
Also fix some incorrect docstrings...
=> Add `indico livesync enqueue` CLI

citadel/indico_citadel/plugin.py, citadel/setup.cfg, livesync/indico_livesync/forms.py, livesync/indico_livesync/plugin.py, payment_paypal/indico_payment_paypal/plugin.py, payment_paypal/setup.cfg, payment_sixpay/indico_payment_sixpay/forms.py, payment_sixpay/setup.cfg, ursh/indico_ursh/plugin.py, ursh/setup.cfg, vc_dummy/indico_vc_dummy/plugin.py, vc_dummy/setup.cfg, vc_zoom/indico_vc_zoom/forms.py, vc_zoom/indico_vc_zoom/plugin.py, vc_zoom/setup.cfg
=> Adapt to WTForms 3

storage_s3/README.md, storage_s3/indico_storage_s3/storage.py, storage_s3/setup.cfg
Also include the readme in the pypi metadata
=> Work around nginx url encoding issue in S3 plugin

recaptcha/indico_recaptcha/client/Captcha.jsx
=> ReCaptcha: Support usage in a wtform

_meta/setup.cfg, citadel/setup.cfg, cloud_captchas/setup.cfg, livesync/setup.cfg, livesync_debug/setup.cfg, owncloud/setup.cfg, payment_manual/setup.cfg, payment_paypal/setup.cfg, payment_sixpay/setup.cfg, piwik/setup.cfg, previewer_code/setup.cfg, previewer_jupyter/setup.cfg, storage_s3/setup.cfg, themes_legacy/setup.cfg, ursh/setup.cfg, vc_dummy/setup.cfg, vc_zoom/setup.cfg
Updated dependency to Python 3.10
=> Updated dependency to Python 3.10

owncloud/README.md, owncloud/indico_owncloud/client/style.scss, owncloud/setup.cfg, themes_legacy/README.md, themes_legacy/indico_themes_legacy/themes/compact.scss, themes_legacy/setup.cfg
=> Adapt to sass changes

citadel/indico_citadel/schemas_test.py
This PR is about polishing test fixtures in line with the changes in this indico PR https://github.com/indico/indico/pull/6593
=> Clean up test fixtures

prometheus/README.md, prometheus/indico_prometheus/controllers.py, prometheus/pyproject.toml
=> Prometheus: Avoid duplicate response headers

.github/workflows/ci.yml, .github/workflows/pypi.yml
Also use `uv` in all CI jobs where we still used classic pip
Merge indico/indico-gh-actions#1 first!
=> ci: Use astral-sh/setup-uv to install uv
